hashicorp/go-plugin

client.go
client_test.go
plugin_daemonize_unix_test.go
plugin_daemonize_windows_test.go
plugin_test.go

This adds support for reattaching to an already-running plugin process. 
To reattach, you ask the Client for the configuration with `ReattachConfig`. You then pass that into `NewClient` on subsequent calls and you can have multiple clients talking to the same plugin process. You can use `client.Kill` as normal to kill the process.
This is an advanced use case and puts some extra burden on the plugin host to maintain the reattach information and to also kill any zombie plugin processes if they're never reattached.

Support plugin reattachment

---

client.go
client_test.go

If reattaching and a process isn't found, return a useful error.

ErrProcessNotFound

---

process_posix.go
process_windows.go

The windows process does not compile:
```
16:33:14 vendor\src\github.com\hashicorp\go-plugin\process_windows.go:4: imported and not used: "os"
16:33:14 vendor\src\github.com\hashicorp\go-plugin\process_windows.go:18: _pidAlive redeclared in this block
16:33:14 	previous declaration at vendor\src\github.com\hashicorp\go-plugin\process_posix.go:10
16:33:14 vendor\src\github.com\hashicorp\go-plugin\process_windows.go:25: undefined: e
16:33:14 vendor\src\github.com\hashicorp\go-plugin\process_windows.go:26: undefined: e
```
This change fixes those issues.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Fix windows process.

---

server.go
server_test.go

We were leaving the Unix domain sockets in the temp folders for the system to handle before. On long running systems this was causing a problem. We now clean them up manually on listener close.

unix domain sockets should be deleted on listener close

---

client.go
client_test.go
plugin_test.go
rpc_client.go
rpc_server.go
server.go

We were only calling process.Kill before which kills the process without
allowing it to perform any cleanup (defers are never called). This was
leaving around a lot of temporary files over time.
We now add a graceful quit method to the control stream that we attempt
to call first. If that fails, we still force quit, but at least this
gives the process a chance to gracefully exit.
🚧 **NOTE:** Don't merge this. I want to re-review this myself personally and make sure I'm happy with the way we're doing this. I posted this so @alex can review and test with Nomad.

client should attempt graceful quit

---

client.go
client_test.go
plugin_test.go

This fixes an issue that Terraform users were seeing wit periodic hangs.
The unit test without this fix reproduces this hang.
This situation was caused when a plugin fails to start properly (invalid
RPC protocol version for example). In this case, `Start` sets `process`
since the binary started, but it never sets `address` because the plugin
is incompatible and never gets to serve an address.
When calling `Kill` in this situation, it wouldn't no-op since process
is set. Next, it'd call `Client` to get the client to close the
connection, but since `address` is nil Client would start the plugin
binary _again_. This would put the entire Client into a bad state and
would case Kill to fail and hang.
There are more bugs here for sure (not new ones introduced, just others
I found) but I want to …

client.Kill should check for addr before closing Client

---

client.go
client_test.go
plugin_test.go
server.go

This PR adds support for verifying the integrity of a plugin by matching the binary's checksum with an expected checksum. It introduces the notion of a `SecureConfig` which stores the expected checksum and selected hashing method.
It also adds support for providing a TLS config to both the client and server of a plugin.

Plugin Checksumming & TLS support 

---

examples/basic/README.md
examples/basic/commons/greeter_interface.go
examples/basic/main.go
examples/basic/plugin/greeter_impl.go

Had some concern about coupling logics in #19, so I figured to have a try at a better plugin example too. 
Basically, the greeter interface(as well as the rpc and plugin interface) are declared in the `example` package  under `common` directory. 
The actual implementation of `Greeter` is in `plugin` directory. 
In this way, the main won't need to know which implementation the Greeter will be. 
This PR addresses #11

Decoupled plugin example

---

client_test.go
rpc_client.go
rpc_server.go

There was no easy way that a plugin consumer could easily check the health of a plugin connection. This is a simple Ping method to do that.

RPCClient supports Ping to check plugin connection health

---

client.go

We worked around this in Terraform, but I'm proposing this change upstream since it did break legacy behavior of programs updating the go-plugins package.
The legacy behavior for go-plugin was to log everything to the
default log output. The default hclog.Logger has a log level of Info, so
clients that have not updated to provide a custom Logger no longer will
see any output from the plugins.
This updates the default Logger to Trace, so that all output is still
seen by clients
The second commit reduces the verbosity of the plugin stderr output lines. The Logger is already being named "plugin" so the "log from plugin" message is redundant, and we can pass the rest of the unstructured data through as-is, again better preserving the legacy behavior.

Client logging

---

client.go
client_test.go
plugin_test.go

The isJSON checked if the output was valid json of any type, but the
logger only unmarshaled into `map[string]interface{}`. If the line
didn't umarshal correctly, the error was only logged, but the actual
line was lost and the loop continued into a nil pointer dereference.
Always log the raw line if it can't unmarshal into a map.
Fixes https://github.com/hashicorp/terraform/issues/15822

Invalid JSON on stderr crashes Client

---

examples/grpc/plugin-python/plugin.py

Trying to fix the Python example.
```
% python --version                    
Python 3.6.2
```
Test:
```
cd examples/grpc
go build -o kv
export KV_PLUGIN="python plugin-python/plugin.py"
./kv put hello world
./kv get hello
```
will return:
```
b'world'
Written from plugin-python
```

Fix the Python example

---

client.go

Just a nitpicky update of an error message.
It may not be clear what do we mean by "ours" or "us" in this context and it's not clear whether the error message is coming from a plugin or core (as they tend to have a single UI exposed to the user).

Clarify error message when API versions don't match

---

server.go

This will allow a plugin to use go-plugin's logger to pass logs back to the client.

Allow the server's logger to be passed in via the ServeConfig

---

grpc_server.go

Small cosmetic fix.
For what its worth, I couldn't build or run the tests because there's no vendor dir and there doesn't seem to be any dep management, so I was missing some stuff.

Fix small typo in gRPC plugin error message

---

client_test.go
rpc_client_test.go
testing.go

These changes are relatively obvious; the one that might cause a little
heartburn is declaring a package-level variable for test stdout/err, but
given the control flow of the test functions it's either that or modify
the test function APIs. I'm happy to do the latter if it's deemed to not
be a big deal, since they're test functions.

Make the tests pass the race detector

---

examples/bidirectional/main.go
examples/bidirectional/plugin-go-grpc/main.go
examples/bidirectional/shared/grpc.go
examples/bidirectional/shared/interface.go

This PR fixes the GRPC bidirectional example in examples/. The import paths were wrong and  the plugin.GRPCPlugin interface was not implemented properly thus the example was not usable as documented in the README.

fix broken GRPC bidirectional example

---

client.go

Fixes #44 
Remove the last usage of the standard `log` package so we're all `hclog` now.
This removes a log statement that isn't recreated anywhere else. I tried putting the statements into `client.Kill` but it gets pretty noisy. I also realized that clients aren't named right now so if you launch a bunch of plugins you invariably get a lot of untargeted "Kill requested" type logs which aren't helpful.
I think it may be better to just remove this for now.

Remove "log" package

---

examples/grpc/shared/interface.go

This PR fixes the `plugin-go-grpc` example to use the updated `GRPCPlugin` interface introduced in #52 and #55.
Prior to this change attempts to initialise the plugin would fail with an `...is not a GRPC-compatible plugin` error.

Fix plugin-go-grpc example

---

client.go

The race detector was complaining about these lines, and it's more performant to not create a new logger for each log line. 
I'm not sure why we need to explicitly add the timestamp to the log arguments, but I left it incase something is using it.

client: reuse the same logger

---

client.go
client_test.go
examples/grpc/plugin-go-grpc/main.go
examples/grpc/shared/interface.go
examples/negotiated/.gitignore
examples/negotiated/README.md
examples/negotiated/main.go
examples/negotiated/plugin-go/main.go
grpc_client_test.go
plugin_test.go
server.go

This is an initial implementation of backwards compatible protocol version negotiation.
The development version if Terraform was implementing a similar mechanism to allow grpc plugins to be backward compatible with previous core versions, but the utility may be generally useful to other users of go-plugin.
The basic design is that rather than having a single `ProtocolVersion` defined in the handshake, the server and client config each have a mapping of protocol versions to plugin sets (`VersionedPlugins`). The client versions are communicated to the server as a comma separated list in the `PLUGIN_PROTOCOL_VERSIONS` environment variable.
The server iterates through the `PLUGIN_PROTOCOL_VERSIONS` values in descending order, and returns the first matching plugin version, along with the …

protocol version negotiation

---

client.go
examples/grpc/main.go
examples/grpc/shared/interface.go

Closes #78 
```
root@b05297468e24:/go/src/github.com/hashicorp/go-plugin/examples/grpc# KV_PLUGIN=./test ./main get test
2018-09-26T16:14:54.358Z [DEBUG] plugin: starting plugin: path=/bin/sh args="[sh -c ./test]"
2018-09-26T16:14:54.359Z [DEBUG] plugin: waiting for RPC address: path=/bin/sh
2018-09-26T16:15:15.909Z [DEBUG] plugin: plugin process exited: path=/bin/sh
2018-09-26T16:15:15.914Z [DEBUG] plugin.sh: Killed
Error: plugin exited before we could connect
```
```
root@b05297468e24:/go/src/github.com/hashicorp/go-plugin/examples/grpc# KV_PLUGIN=./test ./main get test
2018-09-26T16:23:03.051Z [DEBUG] plugin: starting plugin: path=/bin/sh args="[sh -c ./test]"
2018-09-26T16:23:03.052Z [DEBUG] plugin: plugin started: path=/bin/sh pid=1471
2018-09-26T16:23:03.052Z [DEBUG] plugin: waiting …
```

Client: Add more debug details to log

---

client.go

The Kill method is documented as safe to call multiple times, but because the process handle is not removed after the first time, it results in logged errors. 
In troubleshooting this, it also turns out that the child process is never gracefully terminated. I had to remove that from the scope of this PR due to time constraints (and the lack of a simple cross-platform solution), but there is now a log message and associated comment in the source. A POSIX solution is quite simple, with a signal handler to call Stop on the GRPCServer, but that doesn't leave a good solution for Windows. Another option is to implement a control protocol over the plugin's Stdin stream, but that can be left for further discussion.

make sure Kill is idempotent

---

client.go
client_test.go
log_entry.go

bufio.Scanner will abort when it encounters a line longer than it can
buffer. Scan the lines manually, only unmarshalling those that fit in the
line buffer.
This fixes https://github.com/hashicorp/terraform/issues/20325

don't abort reading stderr on long lines

---

client.go
client_test.go
plugin_test.go

Don't drop json output if it's missing a log level. Log the original
line rather than as key-value data, since it likely wasn't intended for
hclog. Even if plugins try to avoid sending raw json objects, it's hard
to avoid if they are writing strings containing newlines (e.g. http
responses), which will be broken into multiple messages by the plugin
client.
Most plugins using go-plugin were previously using the convention of
prefixing log lines with the log level as `[LEVEL]`. Use these prefixes
if available to set the log level.

Log unexpected json, and set levels for plain text logs

---

client.go
client_test.go
plugin_test.go

The prefix checks were reversed in #106.
Add another test checking a less inclusive log level.

fix text log level checks

---

docs/internals.md
server.go

This PR addresses the case where `PLUGIN_MIN_PORT` and/or `PLUGIN_MAX_PORT` are not set and thus treated as empty strings. In this case, `strconv.ParseInt` will error and and the plugin will fail to run.
This PR sets those values as 0 if not provided and lets the OS handle the port assignment (by effectively giving it an address of `127.0.0.1:0`). It also handles the case where the min port might be provided as a value larger than the max port, which would skip listener instantiation and error with "Couldn't bind plugin TCP listener".
Related to https://github.com/hashicorp/vault/issues/6587

listener/tcp: better handling of min/max port env vars

---

client.go

Signed-off-by: Steve Kriss <krisss@vmware.com>
Fixes #116 
cc @jbardin

ensure we finish reading stderr pipe before calling cmd.Wait()

---

client.go

This fix causes no change in behavior on Unix systems, and only
affects the error return type from reattach() when the reattach data
provided has a non-existent pid on Windows.
With this change in place, reattach() will now consistently return
ErrProcessNotFound on both Windows and Unix systems when the process
is indeed not found.
I encountered this while writing a Windows Nomad Task Driver plugin,
here's more context from the Nomad perspective:
The Reattach info Nomad stores can get stale, whereby the pid no
longer refers to a live process.
This has happened to me regularly (but not always) when
troubleshooting plugin development as I'm testingn what happens when
Nomad is forcefully killed and restarted.
On Windows, when the go-plugin code calls FindProcess with as stale
pid, the …

Return a meaningful reattach error for non-existent pids on Windows

---

server.go

While trying to decrease log noise prior to the Nomad 0.9.0 release, I noticed these log lines on agent shutdown (1 or 2 lines per task depending on driver):
```
2019-01-18T12:45:56.342-0800 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon.nomad: plugin received interrupt signal, ignoring: alloc_id=51df16f9-b8dd-2a02-0976-3205f9a53c4a task=redis count=1 @module=logmon timestamp=2019-01-18T12:45:56.310-0800
```
I found their source here:
https://github.com/hashicorp/go-plugin/blob/f444068e8f5a19853177f7aa0aea7e7d95b5b528/server.go#L336-L346
~Is this log message useful to anyone? I don't believe it is to Nomad. If it is not useful I'd propose merging this PR.~ Testing advice welcome. I've only manually tested with Nomad.
*Update:* Found out it is useful during development (see …

ignore interrupts instead of manually eating them

---

client.go

It is simpler to use `strconv.Atoi(s)` than `strconv.ParseInt(s, 10, 0)`
https://golang.org/pkg/strconv/#Atoi

Simplify string to int.

---

go.mod
go.sum
grpc_client_test.go
grpc_server.go

Closes #137 
Similar to our usage of the standard gRPC health service, also register the standard reflection service.

Register grpc reflection service

---

grpc_stdio.go

Fixes regression introduced by #135 when client uses latest version of this package and plugin is compiled with earlier version.
Before this fix, my client log were flooded with the following messages:
```
DBUG[04-07|14:04:20] waiting for stdio data
EROR[04-07|14:04:20] error receiving data err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
```
With these fixes I only receive the following warning message when plugin starts:
```
DBUG[04-07|14:04:20] waiting for stdio data
WARN[04-07|14:04:20] received EOF, stopping recv loop  err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
```

Handle stdio service not implemented

---

client_test.go
plugin_test.go
server.go

This lets the plugin more carefully control the address it wants to
listen on. This is an advanced use case and not typically necessary.
However, it has its uses if you want to force a plugin to serve on a
specific network.

ServeConfig supports a manual listener

---

client.go
client_test.go
plugin_test.go
server.go
server_test.go

This is a special configuration on the plugin server (the plugin side)
that enables running the plugin in-process and eases many of the
behaviors around that.
The desire to do this is for more easily using `go test` (and similar)
with plugins. This mechanism allows the plugin serving to start up
in-process, to grab a ReattachConfig, and to be able to send that
ReattachConfig to some other plugin client for connection.
Behaviorally, this prevents plugin serving from exiting the process with
os.Exit, prevents taking over os.Stdout in such a hostile way, prevents
connection info going to os.Stdout which floods the test logs, etc.
The expected usage can sort of be seen in our own test that I wrote
for this feature. See `TestServer_testMode`. You'd start the plugin 
in test mode in the same …

Add a test mode to enable testing plugins with `go test` more easily, Delve integration, etc.

---

grpc_stdio.go

Return after all grpc stream errors in in the stdio client, as any
stream error is final.
Reduce EOF exit log to DEBUG. This case is unavoidable, and causes
unnecessary log noise.

grpc stream errors are terminal

---

client.go
server.go
server_test.go

This PR adds the (already-determined) `ProtocolVersion` to `ReattachConfig`. This information was not captured previously, so a caller connecting to a running process had no way of knowing what `ProtocolVersion` had been negotiated:  `client.NegotiatedVersion` would always return `0`.

add ProtocolVersion to ReattachConfig

---

client.go
grpc_client.go

Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>
Resolve issue #166 
In order to connect the inter-process traces between implementations of `go-plugin` and its peer services, we have to inject the existing tracing context from the client side while extracting context should also be done from the server side.
No necessary since we can already do the following, (excerpted from `jaeger` plugin from our private repository) 
```go
grpc.ServeWithGRPCServer(
store.NewAliyunSLSStore(&appConfig, logger),
func(options []googleGRPC.ServerOption) *googleGRPC.Server {
return plugin.DefaultGRPCServer([]googleGRPC.ServerOption{
googleGRPC.UnaryInterceptor(otgrpc.OpenTracingServerInterceptor(tracer)),
googleGRPC.StreamInterceptor(otgrpc.OpenTracingStreamServerInterceptor(tracer)),
})
},
)
```
The only …

Add DialOptions field to Config struct

---

client_posix_test.go
go.mod
go.sum
process_posix.go
rpc_server.go

This PR trims a spurious log message for plugins using RPC.
When a plugin is shutting down, the plugin host's log will often report an error about `accept unix` / `use of closed network connection` .  Essentially, an `accept` call is getting invoked on a socket that is already closed.  This PR simply updates the RPC server's `accept` loop to avoid logging that error.
This PR makes an assumption that there are no legitimate debugging situations where this error indication is helpful.
As reported in #72, when using the "basic" example in this repo, the output is the following:
```
2022-01-04T15:36:16.041-0500 [DEBUG] plugin: starting plugin: path=./plugin/greeter args=[./plugin/greeter]
2022-01-04T15:36:16.041-0500 [DEBUG] plugin: plugin started: path=./plugin/greeter pid=10674 …
```

Trim a spurious log message for plugins using RPC

---

client.go
mtls.go
server.go
server_test.go

Currently enabling AutoMTLS when connecting from a plugin process back to the host results in the following error:
```
transport: authentication handshake failed: x509: “localhost” certificate is not standards compliant
```
This is similar but not identical to the error described in https://github.com/hashicorp/go-plugin/issues/109 and https://github.com/hashicorp/go-plugin/pull/179
This PR enables the client and server to successfully establish the mTLS connection for bidirectional communication.

automtls: fix bidirectional communication when AutoMTLS is enabled

---

CHANGELOG.md
client.go

so that it is obvious when looking back over the logs as to why your plugin checksum was not validated.

client: log warning when SecureConfig is nil

---

docs/extensive-go-plugin-tutorial.md
examples/basic/main.go
examples/basic/plugin/greeter_impl.go
examples/basic/shared/greeter_interface.go

Fix examples/basic/commons go package name
Package name "commons" is more explicit in "commons" dir than "example".

Fix examples/basic/commons go package name

---

rpc_server.go
server_test.go

Ensure the RPCServer Serve function closes the DoneCh when it returns. Add a test that will hang if we don't close the channel.
Fixes https://github.com/hashicorp/go-plugin/issues/216
Log diff after changes using the [basic example](https://github.com/hashicorp/go-plugin/tree/master/examples/basic)
```diff
diff --git a/rpc.log b/rpc.log
index c7237c7..b8ca295 100644
--- a/rpc.log
+++ b/rpc.log
@@ -7,7 +7,6 @@
[DEBUG] plugin: using plugin: version=1
[DEBUG] plugin.greeter: message from GreeterHello.Greet: timestamp=NORMALIZED
Hello!
-[DEBUG] plugin.greeter: NORMALIZED [ERR] plugin: stream copy 'stderr' error: stream closed
[DEBUG] plugin.greeter: NORMALIZED [DEBUG] plugin: plugin server: accept unix NORMALIZED: use of closed network connection
[INFO]  plugin: plugin process exited: …
```

RPCServer: close chan when Serve returns

---

grpc_server.go

Initializing a GRPCServer will do the following:
```go
// Register the broker service
brokerServer := newGRPCBrokerServer()
plugin.RegisterGRPCBrokerServer(s.server, brokerServer)
s.broker = newGRPCBroker(brokerServer, s.TLS)
go s.broker.Run()
```
The current Stop() method omits any handling of the underlying `s.broker`, which means the broker goroutine will leak:
```text
[Goroutine 53 in state select, with github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv on top of the stack:
goroutine 53 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0x29?)
/Users/bflad/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.4/grpc_broker.go:121 +0x58
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0x140003ca190)
/Users/bflad/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.4/grpc_broker.g …
```

Ensure GRPCServer.Stop() calls GRPCBroker.Close()

---

client.go
client_test.go
plugin_test.go
testdata/.gitignore
testdata/Makefile
testdata/README.md
testdata/go.mod
testdata/minimal.go

The current error message shown when a plugin does not respond correctly can be obtuse to the end user of, for example, Vault.
Here, we add potential reasons why the plugin did not respond correctly, and some additional debugging information (provided as a best effort) including the CPU architecture that the plugin was compiled for, the current CPU architecture, and the permissions of the plugin. Hopefully this will help users diagnose why their plugin is not loading.
We also added a `testdata/` directory that is optionally populated with executables in various formats to help test the additional debugging information. The binaries are over 1 MB each though, so are not checked in, and the test will be skipped if they have not been compiled.
The error message comes out looking like:
``` …
```

Add more helpful message on plugin setup failure

---

client.go
notes_unix.go
notes_windows.go

fixes https://github.com/hashicorp/go-plugin/issues/225

fix windows build: move additional notes to new files

---

client.go

In #207 we introduced a warning if the `SecureConfig` is unset. For Nomad and other applications that have "internal" go-plugin consumers where the application runs itself as a plugin, this causes spurious warn-level logs. For Nomad in particular this means every task driver and logmon invocation emits the log, which is our primary operation.
Setting a `SecureConfig` isn't required, and if a given go-plugin consumer requires it to be, this seems more like a programming error than a runtime error. Remove the log line.
Ref https://github.com/hashicorp/nomad/issues/16288

remove logging for missing `SecureConfig`

---

examples/bidirectional/proto/kv.pb.go
examples/bidirectional/shared/grpc.go
examples/bidirectional/shared/interface.go
examples/grpc/proto/kv.pb.go
examples/grpc/shared/grpc.go
go.mod
grpc_client.go
internal/plugin/grpc_broker.pb.go
internal/plugin/grpc_controller.pb.go
internal/plugin/grpc_stdio.pb.go
plugin_test.go
test/grpc/test.pb.go

Reference: https://pkg.go.dev/golang.org/x/net@v0.0.0-20190311183353-d8887717615a/context
Reference: https://github.com/hashicorp/go-plugin/pull/186
Previously, the module was only using `golang.org/x/net/context` import. That package was deprecated with Go 1.7 when its functionality migrated into the standard library `context` package. This Go module already announces Go 1.17 minimum since version 1.4.4 and the `context` types are not exposed as part of any exported API.

deps: Remove direct dependency on golang.org/x/net

---

client.go

As far as I know, there is no method `NewManagedClient`, but managed clients are created using `NewClient` with `ClientConfig.Managed = true`

Update docs for creating managed clients

---

client.go
client_test.go

A set of small follow-ups to #270:
* Make `ClientConfig.Cmd` and `ClientConfig.RunnerFunc` mutually exclusive
* Clients setting `RunnerFunc` can call `ReattachConfig()` but need to supply their own `ReattachFunc` as it can't necessarily be derived from `RunnerFunc`. Exercise `ReattachConfig()` in tests in a way that previously panicked.
* Improve 1 logger line for non-cmd implementations.
* Add `ID()` function to client; accommodates creating a `ReattachFunc` and also useful for client's debug log information.

Make config.Cmd and config.RunnerFunc mutually exclusive

---

client.go
client_test.go
internal/cmdrunner/cmd_reattach.go
internal/cmdrunner/cmd_runner.go
runner/runner.go

* Allows us to properly respect the start timeout for implementations that do long-running work in the Start method.
* Adding context.Context to Wait and Kill makes them more consistent with Start, but is also a bit of a hedge, allowing room in the interface for future features without having to break the API.

Add context argument to runner methods that do work

---

CHANGELOG.md
internal/cmdrunner/cmd_runner.go

Full diff: https://github.com/hashicorp/go-plugin/compare/v1.4.11-rc1...f73a4982b4e3f499c0cd629998b9243f841822c3?expand=1
* client: New `runner.Runner` interface to support clients providing custom plugin command runner implementations [[GH-270](https://github.com/hashicorp/go-plugin/pull/270)]
* Accessible via new `ClientConfig` field `RunnerFunc`, which is mutually exclusive with `Cmd` and `Reattach`
* Reattaching support via `ReattachConfig` field `ReattachFunc`
* client: New `ClientConfig` field `SkipHostEnv` allows omitting the client process' own environment variables from the plugin command's environment [[GH-270](https://github.com/hashicorp/go-plugin/pull/270)]
* client: Add `ID()` method to `Client` for retrieving the pid or other unique ID of a running plugin …

Changelog++ for v1.5.0 tag

---

client.go
client_unix_test.go
grpc_broker.go
grpc_client.go
grpc_server.go
server.go
server_unix_test.go
testing.go

Previously, we only supported setting the group for the server-side socket. This change makes it possible to set it on the client side as well. Also fixes a bug where the gRPC broker on the server side would previously not consume the directory/group environment variables.
I found this bug while dropping capabilities for the container runner in the `github.com/hashicorp/go-secure-stdlib/plugincontainer` package, and saw that it was inadvertently relying on the `DAC_OVERRIDE` capability for the plugin to be able to write to client-side sockets it didn't explicitly have permission to.

Consistently apply Unix socket settings

---

CHANGELOG.md

* server: `PLUGIN_UNIX_SOCKET_DIR` is consistently used for gRPC broker sockets as well as the initial socket [[GH-277](https://github.com/hashicorp/go-plugin/pull/277)]
* client: New `UnixSocketConfig` option in `ClientConfig` to support making the client's Unix sockets group-writable [[GH-277](https://github.com/hashicorp/go-plugin/pull/277)]

Changelog++ for v1.5.1

---

client.go
client_unix_test.go
constants.go
server.go

When running plugins in containers with systemd's [PrivateTmp=true](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateTmp=) setting, the containers are not sub-processes so they are not part of the plugin client's file system namespace - as such `/tmp` is different for the 2 sides of the connection and they can't establish communication.
As a workaround, TMPDIR can be set to something that _is_ the same on both sides like `/home/user/tmp`, but that punctures the PrivateTmp setting for all other uses of `/tmp` as well. This lets us choose a single exception.

Add TempDir option to UnixSocketConfig

---

CHANGELOG.md

client: New `UnixSocketConfig.TempDir` option allows setting the directory to use when creating plugin-specific Unix socket directories [[GH-282](https://github.com/hashicorp/go-plugin/pull/282)]

Changelog++ for v1.5.2

---

CHANGELOG.md

* plugin: Plugins written in other languages can optionally start to advertise whether they support gRPC broker multiplexing.
If the environment variable `PLUGIN_MULTIPLEX_GRPC` is set, it is safe to include a seventh field containing a boolean 
value in the `|`-separated protocol negotiation line.
* Support muxing gRPC broker connections over a single listener [[GH-288](https://github.com/hashicorp/go-plugin/pull/288)]
* client: Configurable buffer size for reading plugin log lines [[GH-265](https://github.com/hashicorp/go-plugin/pull/265)]
* Use `buf` for proto generation [[GH-286](https://github.com/hashicorp/go-plugin/pull/286)]
* deps: bump golang.org/x/net to v0.17.0 [[GH-285](https://github.com/hashicorp/go-plugin/pull/285)]
* deps: bump golang.org/x/sys to v0.13.0 …

Changelog++ for v1.6.0

---

client.go
client_test.go

Fixes https://github.com/hashicorp/go-plugin/issues/298

Make sure we wait for stdout/stderr pipes to be closed before calling Wait()

---

client_test.go

Adds a test-case for #299 that reliably fails before the patch, and reliably passes after it.
I ran `go test -count=100 -run ^TestClient_noStdoutScannerRace$ github.com/hashicorp/go-plugin` on commits 586d14f3dcef1eb42bfb7da4c7af102ec6638668 (but with this test added) and 9b348465c6b69c0e402a226c795b1b23a76798af, and got 100/100 failures and 0/100 failures respectively.

Add test for stdout scanner race with runner.Wait()

---

CHANGELOG.md

BUGS:
* Suppress spurious `os.ErrClosed` on plugin shutdown [[GH-299](https://github.com/hashicorp/go-plugin/pull/299)]
ENHANCEMENTS:
* deps: bump google.golang.org/grpc to v1.58.3 [[GH-296](https://github.com/hashicorp/go-plugin/pull/296)]

Changelog++ for v1.6.1

---

grpc_broker.go

When creating new clients and servers with a `type GRPCBroker`, `grpc.ServerOption`s can be added when using `Accept(id uint32)` and `AcceptAndServe(id uint32, s func([]grpc.ServerOption) *grpc.Server)`, but `grpc.DialOption`s cannot be added when using `Dial(id uint32)`.
This PR proposes adding a `DialWithOptions(id uint32, opts ...grpc.DialOption)` method.
Note: `Dial` could be updated in place without affecting typical uses, but the signature change would still be breaking.
```diff
- Dial(id uint32)
+ Dial(id uint32, opts ...grpc.DialOption)
``` 
(this is the approach proposed in #251)

GRPCBroker: add DialWithOptions

---

internal/cmdrunner/cmd_reattach.go

During reattachment, we look to see if the process corresponding to the stored PID is running. If so, we try to connect to that process. If that fails, we kill the process under the presumption it's not working, and return ErrProcessNotFound.
But during reattachment we don't know that the PID we have is still valid. Which means that the process we're trying to attach to may have exited and a different process has spawned with the same PID. This results in some unrelated process getting silently killed.
This impacts Nomad when running the `rawexec` or `exec` task drivers, because the Nomad agent spawns an "executor" process via go-plugin to control the workloads, and these executors are left running when Nomad exits. If the executors die in the meantime (or the host is rebooted), then we …

reattach: don't kill process on failed reconnection

---

CHANGELOG.md

Derived from https://github.com/hashicorp/go-plugin/compare/v1.6.1...main

changelog for 1.6.2

---

.github/workflows/test.yaml
client.go
client_posix_test.go
client_test.go
examples/bidirectional/shared/grpc.go
grpc_broker.go
grpc_client.go
grpc_client_test.go
grpc_server.go
internal/cmdrunner/cmd_reattach.go
internal/cmdrunner/notes_unix.go
mux_broker.go
plugin_test.go
rpc_client.go
rpc_client_test.go
rpc_server.go
server.go
server_unix_test.go
testing.go

Unhandled errors are now swallowed by assignment to `_`.

fix errcheck lint errors and run it as part of pr checks

---

.github/dependabot.yml

As per the memo: https://go.hashi.co/memo/eng-004,
Enabling the dependabot for identifying and updating the security and version updates in the repositories rather handling it manually.

IND-3869 enabling dependabot

---

client.go
client_logger_test.go
log_entry.go

In callers like HashiCorp Terraform, the plugin logger is completely disabled (`hclog.Off`) by default, but previously go-plugin would nonetheless waste time trying to parse log lines to decide what log level to use when calling into the logger, creating memory allocation garbage and spending time in the JSON parser only to immediately discard the results.
The `hclog.Logger` API exposes information about the log level so that callers can skip doing expensive preparation work unless it will actually be used. This now uses that to totally skip all of the log preparation when the logger is completely disabled, and to skip _some_ of the work if the log line's level is not sufficient to match the logger's level.
Modern Terraform plugins tend to generate quite a lot of log messages and it seems …

Spend less time preparing to write log lines when the logger is disabled
